juju-solutions/matrix

- README.md
I was unable to activate with '. .tox.py35/bin/activate' but I was able to active with '. .tox/py35/bin/activate' thus this pull request is to confirm if the correct path is .tox/py35 or .tox.py35
> Correct activate command

- tests/glitch/test_glitch
- tests/test_2.matrix
> Fixed a missing refactor for the actions -> tasks thing.

- matrix/rules.py
- matrix/tasks/health.py
- matrix/view.py
* Add log message when no suites are found
* Fix colorization of log messages
* Fix colorization of icons in rules panel (top-right)
> Small UI improvements

- README.md
Until libjuju is released to pypi, our instructions need to include
installing using the wheelhouse.  Hopefully this can be reverted very
soon.
> Temporarily update README install instructions

- matrix/main.py
- matrix/rules.py
- matrix/tasks/glitch/main.py
- matrix/utils.py
matrix.log, glitch_plan.yaml, and the crash dump now go in a specified
directory.
@johnsca
> Allow user to set an output dir for artifacts.

- README.md
- matrix/utils.py
- tests/functional/basic_test.py
- tests/functional/gating_test.py
- tests/functional/harness.py
- tox.ini
Independently runs multiple .matrix tests, and cleans up after itself.
Can be invoked with `tox -r -e functional -v`
Should save us some time and worry, going forward.
@johnsca This isn't bad for a time boxed pass at it. lmk if there's anything that especially stands out to you as needing work before we merge it.
> Added basic functional testing.

- matrix/main.py
- tests/functional/env_test.py
Helps us in cloud weather report, where we want to pass the value
through multiple subprocess calls.
@johnsca (This will soon be accompanied by a matching PR in layer-cwr)
> Added support for MATRIX_OUTPUT_DIR env variable.

- matrix/rules.py
Also broke the cleanup out into a separate function, for unit testing.
@johnsca @ktsakalozos @kwmonroe Unit testing the RulesEngine class is a bit of a headache. To test this, I just inserted an artificial `raise Exception("test!")` in the code, and verified that we tried ten times (the original + 9 retries), and slept the appropriate amount of time between each. I did code it so that it would be easy to add a unit test, once we have a decent harness for testing the RulesEngine.
> Added retry loop w/ backoff to model cleanup routine.

- tox.ini
If the current directory is turned into a virtualenv, it will cause tox failures.  We don't recommend this, but we can handle it gracefully.
> Gracefully handle "virtualenv ."

- matrix/tasks/glitch/main.py
- tests/glitch/test_main.py
This branch extracts perform_action from main.glitch().
For Hammer Time, Task, Rule, Bus, Context all don't seem necessary.  I have been able to execute a plan using main.glitch(), but it requires more set-up than seems appropriate.  By extracting perform_action, glitch plans become much easier to use.
In order to do this refactoring, I added unit tests for main.glitch() and perform_action.
It passes tox -r.  I didn't see a preferred linter, so I used flake8.
> Extract perform action

- matrix/rules.py
Fixes this:
```
packages/matrix/matrix.yaml
matrix:378:run: Error adding model: 'Controller' object has no attribute 'get_cloud'
------------------------------------------------------------------------------
matrix:423:cleanup: Error while running crashdump.
Traceback (most recent call last):
File "/usr/local/lib/python3.5/dist-packages/matrix/rules.py", line 419, in cleanup
model_name=context.juju_model.info.name,
AttributeError: 'Attribute' object has no attribute 'info'
```
The distill cause, of course, is that it had an outdated version of libjuju.  However, it should handle the uncreated model gracefully regardless.
> Fix error in cleanup if model creation fails

- matrix/main.py
- matrix/rules.py
Defaults to one hour for non interactive mode, and no timeout for
interactive mode. Controllable with a command line param, as it applies
to an entire test suite.
Should prevent matrix from outlasting the energizer bunny.
@johnsca @kwmonroe @ktsakalozos
> Added timeout to matrix tests.

- matrix/tasks/glitch/main.py
- tests/glitch/test_main.py
... using stuff already built in to python-libjuju. How convenient!
@abentley @johnsca @kwmonroe @ktsakalozos
> Glitch now waits for model to settle.

- matrix/rules.py
The localhost provider not requiring credentials in 2.0 was "working by accident."  2.1 closed that gap and now we always require credentials.
Fixes #93
> Remove special case for localhost provider in credentials logic

- matrix/utils.py
- tests/test_full_stack.py
The full stack test closes the event loop, which conflicts with some of the other tests that use the default loop.
> Fix "loop closed" error when running full stack test

- MANIFEST.in
- README.md
- setup.py
`python setup.py sdist` now produces a tarball that works with pip
install. (More ways to install!)
Updated version (we haven't done so in a while).
Got rid of "this is an alpha!" scare text. We're now in beta :-)
Changed executable to `juju-matrix`, to be consistent with plans for the
snap. This has the added benefit of making matrix work as a juju
"plugin" -- i.e., it can be run as `juju matrix`.
Changed name of package in setup.py to jujumatrix, to reflect our plans
for posting to pypi without conflicting with the existing "matrix" package.
@tvansteenburgh @johnsca @abentley @kwmonroe @seman @ludostag
> Tweaks for versioning and packaging.

- matrix/rules.py
Matrix now gets credentials from the proper place if JUJU_DATA is
set. This appears to be the only work needed to support JUJU_DATA at
present.
To test, set JUJU_DATA, and bootstrap a controller, and run
juju-matrix -p tests/basic_bundle
@seman @johnsca
> Matrix now respects JUJU_DATA env variable.

- matrix/rules.py
- matrix/utils.py
- tests/functional/gating_test.py
- tests/test_utils.py
It was looking in the context, rather than context.config, for the ha
key. This would only fail tests that were failing anyway, but it
clobbered the original Exception, and replaced it with an Exception
raised by my broken check. Whoops.
@kwmonroe @johnsca @abentley @seman
> Fixed the should_gate test.

- matrix/model.py
Added a default=None for juju_model, which allows the check for
"juju_model=None" to succeed in the teardown. This prevents the case
where you get a lot of "Attribute has no attribute info" spam in the
logs when attempting to cleanup a test where the model failed to deploy.
@johnsca @abentley @seman
> Fixed info spam on model deploy failure.

- matrix/tasks/chaos/actions.py
- tests/chaos.matrix
It's not really necessary to automatically generate reboot and kill_juju_agent actions for
subordinate charms. There's always a parent charm that we can run those
actions against, instead.
Leaving the SUBORDINATE_OK flag in the codebase for now, just in case we
do add an action that needs it.
@johnsca @seman @abentley
> Removed SUBORDINATE_OK flag from reboot and kill_juju_agent

- matrix/main.py
- matrix/utils.py
- tests/test_utils.py
Spells don't need a bundle.yaml. Fixed the check for valid_bundle so
that it checks for a bundle.yaml *or* a metadata.yaml.
@battlemidget @johnsca @seman @abentley
> Fixed issue where we were failing to deploy valid spells.

- matrix/main.py
- matrix/rules.py
This is an Alexandrian solution to our "matrix is too green" bug.
(https://github.com/juju-solutions/matrix/issues/123)
It also makes things a lot nicer in general. External tools calling
matrix still have to include a timeout, because the existing matrix
timeout only covered hangs during a test run; hangs during setup
or teardown could still lead to a hung matrix. And External tools with
a timeout still have to worry about cleaning up matrix models; having an
internal timeout cleanup that only helps in some cases isn't necessary.
This also simplifies the code, and removes a command line param. A win
all around, I think.
@johnsca @kwmonroe
> Remove internal Timeout for matrix tests.
